export const ACTION = {
  IS_SIGNED_IN: "is_signed_in",
  SET_USER: "set_user",
  EDIT_USER_DETAILS: "edit_user_details",
  SET_TOKEN: "set_token",
  SET_USERLIST: "set_user_list",
  SET_PEOPLE_YOU_MAY_KNOW: "people_you_may_know",
  DISPLAY_SINGLE_USERS_DETAILS: "display_single_users_details",
  GET_ALL_POSTS: "get_all_posts",
  CREATE_POST: "create_post",
  EDIT_POST: "edit_post",
  DELETE_POST: "delete_post",
  LIKE_POST: "like_post",
  DISLIKE_POST: "dislike_post",
  GET_ALL_BOOKMARKED_POST: "get_all_bookmarked_post",
  SET_LIKED_ARR: "set_liked_arr",
  DISPLAY_SINGLEUSER_POSTS: "display_single_user_posts",
  SINGLE_POST_DETAILS: "single_post_details",
  SET_HOME_POSTS_ARR: "set_home_posts_arr",
  NEW_BOOKMARKED_ARR: "new_bookmarked_arr",
};
